### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by abcdefuji** [fkyohei/LineBot_Heroku#1]
あれLineBotってSSL必須だった気がするのですが、Herokuってそこらへんどうやってやるんですか？
Heroku触ったこと無くてわからないです :bow:

**Comment by fkyohei** [comment]
特に何もせずhttps://でアクセスできる。
IP固定化するのにアドオン入れる必要があるけど、月500リクエストまで無料のフリープランで開発はなんとかなる。

**Comment by abcdefuji** [comment]
ほーありがとうございます！
Let's EncryptもLine Bot使えないしわざわざ有料の友人のプランに相乗りしてたわ
Herokuで俺もやってみよう

**Comment by fkyohei** [comment]
無料だと通信速度とか気になる部分も多々あったりするけど、Line Botでいろいろ試す分にはまあ許容できる範囲だと思う。
実際に運用しようとかだとちときついけど。
進捗あったら共有してくれたらありがたい！
